# Generated by Django 5.2.6 on 2025-10-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_docente', '0010_add_data_criacao_respostaavaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodocente',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='avaliacaodocente',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='avaliacaodocente',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='avaliacaodocente',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi desativado', null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AlterField(
            model_name='categoriapergunta',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='categoriapergunta',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='categoriapergunta',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='categoriapergunta',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi desativado', null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AlterField(
            model_name='cicloavaliacao',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='cicloavaliacao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='cicloavaliacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='cicloavaliacao',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi desativado', null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi desativado', null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi desativado', null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AlterField(
            model_name='matriculaturma',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='matriculaturma',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='matriculaturma',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='matriculaturma',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi desativado', null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AlterField(
            model_name='perguntaavaliacao',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='perguntaavaliacao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='perguntaavaliacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='perguntaavaliacao',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi desativado', null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AlterField(
            model_name='questionarioavaliacao',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='questionarioavaliacao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='questionarioavaliacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='questionarioavaliacao',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi desativado', null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AlterField(
            model_name='questionariopergunta',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='questionariopergunta',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='questionariopergunta',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='questionariopergunta',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi desativado', null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AlterField(
            model_name='respostaavaliacao',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='respostaavaliacao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='respostaavaliacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='respostaavaliacao',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi desativado', null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi desativado', null=True, verbose_name='Data de Exclusão'),
        ),
    ]
