# Generated by Django 5.2.6 on 2025-10-15 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_docente', '0011_alter_avaliacaodocente_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLembreteCicloTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de Atualização')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_execucao', 'Em Execução'), ('completo', 'Completo'), ('pausado', 'Pausado'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status')),
                ('proximo_envio_em', models.DateTimeField(blank=True, help_text='Data/hora do próximo disparo de lembretes', null=True, verbose_name='Próximo Envio Em')),
                ('total_alunos_aptos', models.PositiveIntegerField(default=0, help_text='Total de alunos matriculados ativos na turma', verbose_name='Total de Alunos Aptos')),
                ('total_respondentes', models.PositiveIntegerField(default=0, help_text='Alunos distintos que já responderam', verbose_name='Total de Respondentes')),
                ('taxa_resposta_atual', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual de alunos que já responderam', max_digits=5, verbose_name='Taxa de Resposta Atual (%)')),
                ('total_emails_enviados', models.PositiveIntegerField(default=0, verbose_name='Total de E-mails Enviados')),
                ('total_falhas', models.PositiveIntegerField(default=0, verbose_name='Total de Falhas')),
                ('rodadas_executadas', models.PositiveIntegerField(default=0, help_text='Número de vezes que a tarefa foi executada', verbose_name='Rodadas Executadas')),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True, verbose_name='Última Execução')),
                ('mensagem_erro', models.TextField(blank=True, help_text='Detalhes do último erro ocorrido', verbose_name='Mensagem de Erro')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_lembrete', to='avaliacao_docente.cicloavaliacao', verbose_name='Ciclo de Avaliação')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_lembrete', to='avaliacao_docente.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Job de Lembrete por Turma',
                'verbose_name_plural': 'Jobs de Lembrete por Turma',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoLembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de Atualização')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('falhou', 'Falhou'), ('ignorado', 'Ignorado')], default='pendente', max_length=20, verbose_name='Status')),
                ('rodada', models.PositiveIntegerField(default=1, help_text='Número sequencial do lembrete enviado ao aluno', verbose_name='Rodada')),
                ('tentativas', models.PositiveIntegerField(default=0, help_text='Quantidade de tentativas de envio', verbose_name='Tentativas')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviado Em')),
                ('mensagem_id', models.CharField(blank=True, help_text='Message-ID do e-mail enviado', max_length=255, verbose_name='ID da Mensagem')),
                ('motivo_falha', models.TextField(blank=True, verbose_name='Motivo da Falha')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_lembrete', to='avaliacao_docente.perfilaluno', verbose_name='Aluno')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='avaliacao_docente.joblembretecicloturma', verbose_name='Job de Lembrete')),
            ],
            options={
                'verbose_name': 'Notificação de Lembrete',
                'verbose_name_plural': 'Notificações de Lembrete',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='joblembretecicloturma',
            index=models.Index(fields=['status', 'proximo_envio_em'], name='avaliacao_d_status_708322_idx'),
        ),
        migrations.AddIndex(
            model_name='joblembretecicloturma',
            index=models.Index(fields=['ciclo', 'turma'], name='avaliacao_d_ciclo_i_deeb4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='joblembretecicloturma',
            unique_together={('ciclo', 'turma')},
        ),
        migrations.AddIndex(
            model_name='notificacaolembrete',
            index=models.Index(fields=['job', 'aluno'], name='avaliacao_d_job_id_960212_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacaolembrete',
            index=models.Index(fields=['status', 'enviado_em'], name='avaliacao_d_status_6f388f_idx'),
        ),
    ]
