# Generated by Django 5.2.6 on 2025-10-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_docente', '0012_joblembretecicloturma_notificacaolembrete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='frequencia_lembrete_horas',
            field=models.PositiveIntegerField(default=48, help_text='Intervalo em horas entre cada rodada de lembretes (padrão: 48h)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='limiar_minimo_percentual',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percentual mínimo de respostas por turma para parar envio de lembretes (padrão: 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='max_lembretes_por_aluno',
            field=models.PositiveIntegerField(default=3, help_text='Número máximo de lembretes que um aluno pode receber por ciclo (padrão: 3)'),
        ),
    ]
