# Generated by Django 5.2.6 on 2025-10-19 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_docente', '0013_configuracaosite_frequencia_lembrete_horas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriapergunta',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição opcional (limite: 300 caracteres)', validators=[django.core.validators.MaxLengthValidator(300, message='A descrição deve ter no máximo 300 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='questionarioavaliacao',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição opcional (limite: 300 caracteres)', validators=[django.core.validators.MaxLengthValidator(300, message='A descrição deve ter no máximo 300 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='respostaavaliacao',
            name='valor_texto',
            field=models.TextField(blank=True, help_text='Limite: 300 caracteres', validators=[django.core.validators.MaxLengthValidator(300, message='O comentário deve ter no máximo 300 caracteres.')]),
        ),
    ]
