# Generated by Django 5.2.6 on 2025-11-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_docente', '0014_adicionar_max_length_validacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicloavaliacao',
            name='data_encerramento',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o ciclo foi encerrado manualmente', null=True, verbose_name='Data de Encerramento'),
        ),
        migrations.AddField(
            model_name='cicloavaliacao',
            name='encerrado',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica se o ciclo foi encerrado manualmente (não aceita mais respostas)', verbose_name='Encerrado'),
        ),
    ]
