# Generated by Django 5.2.6 on 2025-11-06
"""
Migration para adicionar índices de performance nos relatórios de professores.

Esta migration adiciona índices compostos nas tabelas mais acessadas durante
a geração de relatórios, otimizando queries que filtram por:
- professor + ciclo (Avaliacao)
- avaliacao + aluno (RespostaAvaliacao)
- turma + status ativo (MatriculaTurma)
- status + data (CicloAvaliacao)
- curso + status ativo (Disciplina)

Ganho esperado: 30-40% de redução no tempo de execução de queries.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacao_docente", "0016_adicionar_lembrete_avaliacao"),
    ]

    operations = [
        # Índice para AvaliacaoDocente - busca por professor e ciclo
        migrations.AddIndex(
            model_name="avaliacaodocente",
            index=models.Index(
                fields=["professor", "ciclo", "ativo"], name="idx_aval_prof_ciclo_ativo"
            ),
        ),
        # Índice para RespostaAvaliacao - busca por avaliação e aluno
        migrations.AddIndex(
            model_name="respostaavaliacao",
            index=models.Index(
                fields=["avaliacao", "aluno"], name="idx_resp_aval_aluno"
            ),
        ),
        # Índice para MatriculaTurma - busca por turma e status
        migrations.AddIndex(
            model_name="matriculaturma",
            index=models.Index(
                fields=["turma", "ativo"], name="idx_matric_turma_ativo"
            ),
        ),
        # Índice para CicloAvaliacao - busca por data e status
        migrations.AddIndex(
            model_name="cicloavaliacao",
            index=models.Index(
                fields=["ativo", "encerrado", "data_inicio"],
                name="idx_ciclo_status_data",
            ),
        ),
        # Índice composto para Disciplina - busca por curso
        migrations.AddIndex(
            model_name="disciplina",
            index=models.Index(fields=["curso", "ativo"], name="idx_disc_curso_ativo"),
        ),
    ]
